# Generated by Django 5.2.4 on 2025-08-19 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_title', models.CharField(max_length=50, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='员工姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('data', models.DateTimeField(verbose_name='入职时间')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miao1.depart')),
            ],
        ),
    ]
