# Generated by Django 5.2.4 on 2025-08-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], default=0, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123456, max_length=64, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
