# Generated by Django 5.2.4 on 2025-08-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0002_user_gender_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
        ),
    ]
