# Generated by Django 5.2.4 on 2025-09-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0003_admin_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_list',
            name='phone',
            field=models.IntegerField(default=1, max_length=60, verbose_name='手机号码'),
            preserve_default=False,
        ),
    ]
