# Generated by Django 5.2.4 on 2025-09-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0005_alter_admin_list_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_list',
            name='phone',
            field=models.CharField(max_length=120, verbose_name='手机号码'),
        ),
    ]
