# Generated by Django 5.2.4 on 2025-09-11 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0006_alter_admin_list_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.CreateModel(
            name='dorm',
            fields=[
                ('dorm_number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='宿舍号')),
                ('bulding', models.CharField(choices=[('D5', 'D5栋'), ('D8', 'D8栋')], default='D5', max_length=8, verbose_name='栋别')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miao1.depart')),
            ],
        ),
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peopole_number', models.IntegerField(verbose_name='人数')),
                ('acount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='水电余额')),
                ('satus', models.SmallIntegerField(choices=[(1, '正常'), (2, '欠费')], default=1, verbose_name='状态')),
                ('dorm_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miao1.dorm')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dorm_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miao1.dorm'),
        ),
    ]
