# Generated by Django 5.2.4 on 2025-09-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0007_remove_user_account_dorm_account_user_dorm_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data',
            field=models.DateField(verbose_name='入职时间'),
        ),
    ]
