# Generated by Django 5.2.4 on 2025-09-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0008_alter_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='dorm_number',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False, verbose_name='宿舍号'),
        ),
    ]
