# Generated by Django 5.2.4 on 2025-09-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0009_alter_dorm_dorm_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='dorm_title',
            field=models.CharField(default='426', max_length=20, verbose_name='宿舍名称'),
        ),
    ]
