# Generated by Django 5.2.4 on 2025-09-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0010_dorm_dorm_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='acount',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='satus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='dorm',
            old_name='bulding',
            new_name='building',
        ),
        migrations.AddField(
            model_name='account',
            name='dorm_title',
            field=models.CharField(default='426', max_length=20, verbose_name='宿舍名称'),
        ),
        migrations.AlterField(
            model_name='account',
            name='dorm_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miao1.dorm'),
        ),
    ]
