# Generated by Django 5.2.4 on 2025-09-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0011_rename_acount_account_account_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='account_number',
            old_name='account',
            new_name='account_number',
        ),
    ]
