# Generated by Django 5.2.4 on 2025-09-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0012_rename_account_account_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account_number',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='account_number',
            new_name='balance_one',
        ),
    ]
