# Generated by Django 5.2.4 on 2025-09-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0013_rename_account_number_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='peopole_number',
            new_name='people_number',
        ),
    ]
