# Generated by Django 5.2.4 on 2025-09-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0014_rename_peopole_number_balance_people_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='depart',
            name='depart_number',
            field=models.CharField(default=6, max_length=50, verbose_name='部门人数'),
        ),
    ]
