# Generated by Django 5.2.4 on 2025-09-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0015_depart_depart_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='dorm_title',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='dorm_title',
        ),
        migrations.AddField(
            model_name='dorm',
            name='user_name',
            field=models.CharField(default='张三', max_length=50, verbose_name='宿舍负责人'),
        ),
    ]
