# Generated by Django 5.2.4 on 2025-09-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0016_remove_balance_dorm_title_remove_dorm_dorm_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_list',
            name='user_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dorm',
            name='user_type',
            field=models.IntegerField(default=0),
        ),
    ]
