# Generated by Django 5.2.4 on 2025-09-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0017_admin_list_user_type_dorm_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorm',
            name='user_type',
        ),
    ]
