# Generated by Django 5.2.4 on 2025-09-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miao1', '0018_remove_dorm_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='user_type',
            field=models.IntegerField(default=0),
        ),
    ]
